name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install awesome-lint
      run: npm init -y && npm install awesome-lint
        
    - name: Run awesome-lint
      run: ./node_modules/.bin/awesome-lint
